### ISSUE TITLE
ExceptionsManager.js:63 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zhw2590582** [lvming6816077/react-native-pullRefreshScrollView#11]
<img src='https://cdn.rawgit.com/zhw2590582/grunt_config/master/WX20170104-175137%402x.png' width='300px'>

是直接拿你的demo运行出错的，是不是我哪里操作不对了呢？

**Comment by lvming6816077** [comment]
已经修复 使用最新的版本即可





------------------ 原始邮件 ------------------
发件人: "Harvey Zack";<notifications@github.com>;
发送时间: 2017年1月4日(星期三) 下午5:55
收件人: "lvming6816077/react-native-pullRefreshScrollView"<react-native-pullRefreshScrollView@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [lvming6816077/react-native-pullRefreshScrollView]ExceptionsManager.js:63 Cannot read property 'length' of undefined (#11)





 
是直接拿你的demo运行出错的，是不是我哪里操作不对了呢？
